### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by T1MOXA** [ibm-dev-incubator/demoparser#1]
```
Installing collected packages: csgo-demoparser
  Running setup.py install for csgo-demoparser ... error
    Complete output from command c:\users\t1moxa\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\T1MOXA\\AppData\\Local\\Temp\\pip-install-37z6pu4u\\csgo-demoparser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\T1MOXA\AppData\Local\Temp\pip-record-igv0z_bu\install-record.txt --single-version-externally-managed --compile:
    running install
    [pbr] Generating AUTHORS
    [pbr] AUTHORS complete (0.0s)
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\T1MOXA\AppData\Local\Temp\pip-install-37z6pu4u\csgo-demoparser\setup.py", line 35, in <module>
        "language_level": 3
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\t1moxa\appdata\local\temp\pip-install-37z6pu4u\csgo-demoparser\.eggs\pbr-4.2.0-py3.7.egg\pbr\packaging.py", line 213, in run
        return du_install.install.run(self)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\T1MOXA\AppData\Local\Temp\pip-install-37z6pu4u\csgo-demoparser\demoparser\_setup_hooks.py", line 21, in run
        self.protoc()
      File "C:\Users\T1MOXA\AppData\Local\Temp\pip-install-37z6pu4u\csgo-demoparser\demoparser\_setup_hooks.py", line 18, in protoc
        ], check=True)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\subprocess.py", line 453, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1100, in _execute_child
        args = list2cmdline(args)
      File "c:\users\t1moxa\appdata\local\programs\python\python37-32\lib\subprocess.py", line 511, in list2cmdline
        needquote = (" " in arg) or ("\t" in arg) or not arg
    TypeError: argument of type 'NoneType' is not iterable

    ----------------------------------------
Command "c:\users\t1moxa\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\T1MOXA\\AppData\\Local\\Temp\\pip-install-37z6pu4u\\csgo-demoparser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\T1MOXA\AppData\Local\Temp\pip-record-igv0z_bu\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\T1MOXA\AppData\Local\Temp\pip-install-37z6pu4u\csgo-demoparser\
```

**Comment by rmoe** [comment]
You need the protocol buffer compiler (protoc) installed. You can get it here: https://github.com/protocolbuffers/protobuf/releases

**Comment by T1MOXA** [comment]
Thank you so much

**Comment by T1MOXA** [comment]
I found more errors, can you tell me why they occur ?

```
KeyError: 27
Exception ignored in: 'demoparser.demofile.DemoFile.handle_game_event'
KeyError: (27,)
KeyError: 27
Exception ignored in: 'demoparser.demofile.DemoFile.handle_game_event'
KeyError: (27,)
KeyError: 69
Exception ignored in: 'demoparser.demofile.DemoFile.handle_user_message'
KeyError: (69,)
KeyError: 69
Exception ignored in: 'demoparser.demofile.DemoFile.handle_user_message'
KeyError: (69,)
KeyError: 69
Exception ignored in: 'demoparser.demofile.DemoFile.handle_user_message'
KeyError: (69,)
Traceback (most recent call last):
  File "demoparser\demofile.pyx", line 503, in demoparser.demofile.DemoFile.class_by_net_message_type
AttributeError: module 'demoparser.protobufs.netmessages_pb2' has no attribute 'CSVCMsg_EntityMessage'
Exception ignored in: 'demoparser.demofile.DemoFile.handle_demo_packet'
Traceback (most recent call last):
  File "demoparser\demofile.pyx", line 503, in demoparser.demofile.DemoFile.class_by_net_message_type
AttributeError: module 'demoparser.protobufs.netmessages_pb2' has no attribute 'CSVCMsg_EntityMessage'
Traceback (most recent call last):
  File "1.py", line 10, in <module>
    df.parse()
  File "demoparser\demofile.pyx", line 112, in demoparser.demofile.DemoFile.parse
  File "demoparser\demofile.pyx", line 147, in demoparser.demofile.DemoFile.parse
demoparser.demofile.CommandError: Unrecognized command
```

code:
```
from demoparser.demofile import DemoFile
data = open('demo.dem', 'rb').read()
df = DemoFile(data)
df.parse()
```

Perhaps I should create a new issue for this?

**Comment by rmoe** [comment]
I moved this to a new issue

**Comment by T1MOXA** [comment]
I recently reinstalled the system and again encountered an error from the first message, although the `protoc `seems to be installed correctly.

```
C:\Users\T1MOX4>protoc --version
libprotoc 3.6.1
```
