### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by agentcap** [ibm-dev-incubator/demoparser#15]
When trying to install using the following commands
```
pip install -r requirements.txt`
pip install .
```
I am getting the following error

```
Processing /home/pradeep/Files/Kyuker/data/custom-parser/demoparser
Collecting suitcase (from csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/a6/18/5812df598febe51d87287feb82d6b37cf56a358ec11f89bc8e089971ee9f/suitcase-0.11.0-py3-none-any.whl
Collecting cython (from csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/e7/bd/59054534d09830394470c14e4dd4a2e8fa64ac14559095a044208bf34c18/Cython-0.29.7-cp35-cp35m-manylinux1_x86_64.whl
Collecting protobuf (from csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/81/59/c7b0815a78fd641141f24a6ece878293eae6bf1fce40632a6ab9672346aa/protobuf-3.7.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting sphinx (from csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/9a/b0/a8cf1d35237aebefd63f05543ed49ea24d302239828ca89409b0c1a35b27/Sphinx-2.0.1-py2.py3-none-any.whl
Collecting six (from suitcase->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
Collecting sphinxcontrib-devhelp (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/b0/a3/fea98741f0b2f2902fbf6c35c8e91b22cd0dd13387291e81d457f9a93066/sphinxcontrib_devhelp-1.0.1-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/51/d2/181e37a5f0c883f0ca000d94e01a3c2bdc2178227ba5a80046004854459c/Pygments-2.4.1-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting docutils>=0.12 (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting sphinxcontrib-applehelp (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/13/9a/4428b3114d654cb1cd34d90d5e6fab938d5436f94a571155187ea1dd78b4/sphinxcontrib_applehelp-1.0.1-py2.py3-none-any.whl
Collecting requests>=2.5.0 (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting sphinxcontrib-jsmath (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl
Collecting imagesize (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Collecting sphinxcontrib-htmlhelp (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/e4/35/80a67cc493f4a8a9634ab203a77aaa1b84d79ccb1c02eca72cb084d2c7f7/sphinxcontrib_htmlhelp-1.0.2-py2.py3-none-any.whl
Collecting sphinxcontrib-qthelp (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/ce/5b/4747c3ba98b3a3e21a66faa183d8f79b9ded70e74212a7988d236a6eb78a/sphinxcontrib_qthelp-1.0.2-py2.py3-none-any.whl
Collecting packaging (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting sphinxcontrib-serializinghtml (from sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/57/b3/3648e48fa5682e61e9839d62de4e23af1795ceb738d68d73bd974257a95c/sphinxcontrib_serializinghtml-1.1.3-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/6e/57/d40124076756c19ff2269678de7ae25a14ebbb3f6314eb5ce9477f191350/MarkupSafe-1.1.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.5.0->sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.5.0->sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.5.0->sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.5.0->sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->sphinx->csgo-demoparser===0.0.1.dev23)
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Installing collected packages: six, suitcase, cython, setuptools, protobuf, sphinxcontrib-devhelp, Pygments, alabaster, MarkupSafe, Jinja2, docutils, pytz, babel, sphinxcontrib-applehelp, certifi, urllib3, chardet, idna, requests, sphinxcontrib-jsmath, imagesize, sphinxcontrib-htmlhelp, sphinxcontrib-qthelp, pyparsing, packaging, snowballstemmer, sphinxcontrib-serializinghtml, sphinx, csgo-demoparser
  Running setup.py install for csgo-demoparser ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-lir_b23e-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xx43t_7g-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Compiling demoparser/props.pyx because it depends on /home/pradeep/.local/lib/python3.5/site-packages/Cython/Includes/libc/math.pxd.
    Compiling demoparser/bitbuffer.pyx because it depends on /home/pradeep/.local/lib/python3.5/site-packages/Cython/Includes/cpython/weakref.pxd.
    Compiling demoparser/demofile.pyx because it depends on /home/pradeep/.local/lib/python3.5/site-packages/Cython/Includes/libc/__init__.pxd.
    [1/3] Cythonizing demoparser/demofile.pyx
    [2/3] Cythonizing demoparser/props.pyx
    [3/3] Cythonizing demoparser/bitbuffer.pyx
    running install
    [pbr] Writing ChangeLog
    [pbr] Generating ChangeLog
    [pbr] ChangeLog complete (0.0s)
    [pbr] Generating AUTHORS
    [pbr] AUTHORS complete (0.0s)
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-lir_b23e-build/setup.py", line 35, in <module>
        "language_level": 3
      File "/home/pradeep/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-lir_b23e-build/.eggs/pbr-5.2.0-py3.5.egg/pbr/packaging.py", line 218, in run
        return du_install.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-lir_b23e-build/demoparser/_setup_hooks.py", line 21, in run
        self.protoc()
      File "/tmp/pip-lir_b23e-build/demoparser/_setup_hooks.py", line 18, in protoc
        ], check=True)
      File "/usr/lib/python3.5/subprocess.py", line 693, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1474, in _execute_child
        executable = os.fsencode(executable)
      File "/usr/lib/python3.5/os.py", line 862, in fsencode
        raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
    TypeError: expect bytes or str, not NoneType
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-lir_b23e-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xx43t_7g-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-lir_b23e-build/
```

**Comment by MNP666** [comment]
Do you have the protocl buffer compilers installed? from the traceback it looks to me as the distutils.spawn.find_executable cannot find it (see _setup_hooks.py). There is also a closed issue about that.

**Comment by ckarrie** [comment]
`sudo apt-get install protobuf-compiler` fixed that

**Comment by kieran-cooney** [comment]
Thanks for raising; this solved my problem too.
