### ISSUE TITLE
PBR throws error when installing on windows

### ISSUE THREAD

**Issue by MNP666** [ibm-dev-incubator/demoparser#17]
Hello,

I have tried to install directly from github, running the pip install -r requirements.txt to make sure everthing needed was install and correct version. When I try to run the 'pip install .' command I following error:

> (py36) C:\Users\mrnor\Documents\GitHub\demoparser>pip install .
Processing c:\users\mrnor\documents\github\demoparser
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Compiling demoparser/util.pyx because it changed.
    Compiling demoparser/props.pyx because it changed.
    Compiling demoparser/bitbuffer.pyx because it changed.
    Compiling demoparser/demofile.pyx because it changed.
    [1/4] Cythonizing demoparser/bitbuffer.pyx
    [2/4] Cythonizing demoparser/demofile.pyx
    [3/4] Cythonizing demoparser/props.pyx
    [4/4] Cythonizing demoparser/util.pyx
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\mrnor\appdata\local\temp\pip-req-build-x_2u4jhm\.eggs\pbr-5.4.2-py3.6.egg\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\mrnor\appdata\local\temp\pip-req-build-x_2u4jhm\.eggs\pbr-5.4.2-py3.6.egg\pbr\util.py", line 270, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\users\mrnor\appdata\local\temp\pip-req-build-x_2u4jhm\.eggs\pbr-5.4.2-py3.6.egg\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\users\mrnor\appdata\local\temp\pip-req-build-x_2u4jhm\.eggs\pbr-5.4.2-py3.6.egg\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\users\mrnor\appdata\local\temp\pip-req-build-x_2u4jhm\.eggs\pbr-5.4.2-py3.6.egg\pbr\hooks\metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "c:\users\mrnor\appdata\local\temp\pip-req-build-x_2u4jhm\.eggs\pbr-5.4.2-py3.6.egg\pbr\packaging.py", line 874, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name demoparser was given, but was not able to be found.
    error in setup command: Error parsing C:\Users\mrnor\AppData\Local\Temp\pip-req-build-x_2u4jhm\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name demoparser was given, but was not able to be found.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\mrnor\AppData\Local\Temp\pip-req-build-x_2u4jhm\

I have tried it in two different enviroments (3.6 and 3.7), and in both I get the same error. 
setuptools:  in c:\users\mrnor\anaconda3\envs\py36\lib\site-packages (41.0.1)
pbr: in c:\users\mrnor\anaconda3\envs\py36\lib\site-packages (5.4.2)

I can install it on my linux partition, so it is either something with my windows environments (quite possibly) or something with windows installations. I have made a fork where I'll try to fix it - tips would be appreciated!

**Comment by matiasjosecastro** [comment]
Where you able to fix this?
